In [102]:
import random
import numpy as np
import networkx as nx 
from dijkstar import Graph, find_path

In [103]:
def generate_instance_matrix(nb_vertex, min_weight, max_weight, density):
  graph = np.ones((nb_vertex, nb_vertex)) * np.inf
  for i in range(nb_vertex - 1):
    for j in range(i+1, nb_vertex):
      if random.uniform(0, 1) < density:
        weight = random.randint(min_weight, max_weight)
        graph[i, j] = weight
        graph[j, i] = weight
  for i,line in enumerate(graph):
    index_zeros = np.where(line == np.inf)[0]
    index_zeros = np.delete(index_zeros, np.where(index_zeros == i))
    for j in range(len(index_zeros) - (nb_vertex - 3)):
      index = random.choice(index_zeros)
      index_zeros = np.delete(index_zeros, np.where(index_zeros == index))
      weight = random.randint(min_weight, max_weight)
      graph[i, index] = weight
      graph[index, i] = weight
  return graph

def convert_graph(graph):
  graph_dijkstra = Graph()
  for i in range(len(graph)):
    for j in range(len(graph)):
      graph_dijkstra.add_edge(i, j,graph[i][j])
  return graph_dijkstra

def get_distance_between_nodes(graph, i, j):
  if (graph[i][j] != np.inf):
    return graph[i][j], [i, j]
  else:
    if i != j:
      shortest_path = find_path(graph, i,j)
      return shortest_path.total_cost, shortest_path.nodes
    else:
      return 0, None

def get_complete_graph(graph, node_list):
  all_paths = {}
  converted_graph = convert_graph(graph)
  complete_graph = np.zeros((len(node_list), len(node_list)))
  for i in node_list:
    voisins_array = np.delete(node_list, np.where(node_list == i))
    for j in voisins_array:
      distance, path = get_distance_between_nodes(converted_graph, i, j)
      converted_graph_i = np.where(node_list == i)[0][0]
      converted_graph_j = np.where(node_list == j)[0][0]
      complete_graph[converted_graph_i][converted_graph_j] = distance
      all_paths[(converted_graph_i, converted_graph_j)] = path
  return complete_graph, all_paths

def get_random_vertex(size, nb_vertex):
  random_vertex = []
  all_vertex = np.array(range(size))
  for _ in range(nb_vertex):
    value = random.choice(all_vertex)
    random_vertex.append(value)
    all_vertex = np.delete(all_vertex, np.where(all_vertex == value))
  return np.array(random_vertex)

def generate_interval():
  interval = random.choice(range(1,4))
  shift = random.choice(range(0, 11-interval))
  return(shift*60, (shift+interval)*60)

def generate_instance(nb_vertex_matrix, min_weight, max_weight, density, random_vertex):
  graph = generate_instance_matrix(nb_vertex_matrix, min_weight, max_weight, density)
  complete_graph, all_paths = get_complete_graph(graph, random_vertex)
  return graph, complete_graph, all_paths

def get_complete_path(path, all_paths):
  complete_path = []
  for i in range(len(path) - 1):
    complete_path.extend(all_paths[(path[i], path[i+1])][:-1])
    if i == len(path) - 2:
      complete_path.append(all_paths[(path[i], path[i+1])][-1])
  return complete_path

def is_path_in_interval(path, complete_graph, interval, vertex):
  weight = 0
  for i in range(np.where(np.array(path) == vertex)[0][0]):
    weight += complete_graph[path[i]][path[i+1]]
  if weight >= interval[0] and weight <= interval[1]:
    return True
  else:
    return False

def generate_neighbours(path, complete_graph, interval, vertex):
  neighbours = []
  for i in range(len(path)):
    for j in range(i + 1, len(path)-1):
      new_neighbour = path.copy()

      new_neighbour[i] = path[j]
      new_neighbour[j] = path[i]
      
      if is_path_in_interval(new_neighbour, complete_graph, interval, vertex) and new_neighbour[0] == new_neighbour[-1]:
        neighbours.append(new_neighbour)
  return neighbours

def generate_random_path(nb_vertex, start_vertex):
  path = np.arange(nb_vertex)
  path = np.delete(path, np.where(path == start_vertex))
  np.random.shuffle(path)
  path = np.append(path, start_vertex)
  path = np.insert(path, 0, start_vertex)
  return path

In [104]:
#variables
nb_vertex_matrix = 100
min_weight = 10
max_weight = 60
density = 0.3
nb_vertex_chosen = 5

In [105]:
#random generation of a list of vertex among all the vertex available
random_vertex = get_random_vertex(nb_vertex_matrix, nb_vertex_chosen)

# generation of the graph, the complete graph and the list of all paths
graph, complete_graph, all_paths =\
generate_instance(
  nb_vertex_matrix = nb_vertex_matrix,
  min_weight = min_weight,
  max_weight = max_weight,
  random_vertex = random_vertex,
  density = density
)

In [106]:
#generate an interval instance
interval = generate_interval()

In [107]:
#generate a random path
path = generate_random_path(nb_vertex_chosen, 0)

In [108]:
# generate the neighbours of a path
neighbours = generate_neighbours(path, complete_graph, (0,50), 1)

In [109]:
# print("graph")
# print(graph)
print("complete_graph")
print(complete_graph)
# print("all_paths")
# print(all_paths)
# print("random_vertex")
# print(random_vertex)
# print("interval")
# print(interval)

complete_graph
[[ 0. 52. 50. 50. 27.]
 [52.  0. 40. 32. 34.]
 [50. 40.  0. 43. 30.]
 [50. 32. 43.  0. 23.]
 [27. 34. 30. 23.  0.]]


In [110]:
complete_path = get_complete_path(path, all_paths)

In [111]:
print(random_vertex)
print(path)
print(complete_path)

[24 82 63 39 78]
[0 4 3 2 1 0]
[24, 53, 78, 69, 39, 45, 63, 57, 61, 82, 51, 90, 53, 24]


In [112]:
from pulp import *
import numpy as np


X=[]
P = []
X_dict = {}
True_tab = []



# variables du problème
for i in range(len(complete_graph)):
    for j in range(len(complete_graph)):
        X.append(LpVariable("X_" + str(i) + "_" + str(j), 0, 1, LpInteger))
        X_dict[("X_" + str(i) + "_" + str(j))] = LpVariable("X_" + str(i) + "_" + str(j), 0, 1, LpInteger)
        P.append(complete_graph[i][j])

# probleme
prob = LpProblem("plus court chemin", LpMinimize)

# objectif
# Somme de la multiplication des poids de chaque arc
prob += lpSum([P[i] * X[i] for i in range(len(P))])

# contraintes
# La somme d'un arc doit etre egale a 1
X_np = np.array(X)
X_np_reshape = X_np.reshape(len(complete_graph), len(complete_graph))

for i in range(len(X_np_reshape)):
    prob += lpSum(X_np_reshape[i]) == 1
    prob += X_np_reshape[i][i] == 0
    for j in range(len(X_np_reshape)):
        if i != j:
            prob += X_np_reshape[i][j] + X_np_reshape[j][i] <= 1


prob.solve()
print(LpStatus[prob.status])
print("Min=", value(prob.objective))

# variables resultat
for v in prob.variables():
    print("%s=%.2f"%(v.name,v.varValue), end=', ')

Optimal
Min= 146.0
X_0_0=0.00, X_0_1=0.00, X_0_2=0.00, X_0_3=0.00, X_0_4=1.00, X_1_0=0.00, X_1_1=0.00, X_1_2=0.00, X_1_3=0.00, X_1_4=1.00, X_2_0=0.00, X_2_1=0.00, X_2_2=0.00, X_2_3=0.00, X_2_4=1.00, X_3_0=0.00, X_3_1=1.00, X_3_2=0.00, X_3_3=0.00, X_3_4=0.00, X_4_0=0.00, X_4_1=0.00, X_4_2=0.00, X_4_3=1.00, X_4_4=0.00, 

In [113]:
nb_iterations=1000 #Dans la boucle while de la boucle principale
T0 = 300 #Température de départ
Tmin = 1e-2 #Température minimale
tau = 1e4 #Pour la loi de refroidissement

In [114]:
def distance_tot(matrice,path_matrix):
    distance_tot = 0
    ind = 2
    points = [0,0]
    for i in range(len(path_matrix)):
        if i == 0:
            points = path_matrix[0:2]
            distance_tot += get_distance_between_nodes(matrice,points[0],points[1])[0]
        else:
            if (ind <= len(matrice)):
                points = path_matrix[ind-1:ind+1]
                distance_tot += get_distance_between_nodes(matrice,points[0],points[1])[0]
                ind += 1
    return distance_tot

print(distance_tot(complete_graph,path))

185.0


In [115]:
def randomSolution(complete_graph):
    vertex = list(range(len(complete_graph)))
    solution = []

    for i in range(len(complete_graph)):
        randomVertex = vertex[random.randint(0, len(vertex) - 1)]
        solution.append(randomVertex)
        vertex.remove(randomVertex)

    return solution


def routeLength(complete_graph, solution):
    routeLength = 0
    for i in range(len(solution)):
        routeLength += complete_graph[solution[i - 1]][solution[i]]
    return routeLength

def generate_neighbours(path, complete_graph, interval, vertex):
  neighbours = []
  for i in range(len(path)):
    for j in range(i + 1, len(path)-1):
      new_neighbour = path.copy()

      new_neighbour[i] = path[j] 
      new_neighbour[j] = path[i]
      
      if is_path_in_interval(new_neighbour, complete_graph, interval, vertex) and new_neighbour[0] == new_neighbour[-1]:
        neighbours.append(new_neighbour)
  return neighbours

def getBestNeighbor(complete_graph, neighbours):
    bestRouteLenght = routeLength(complete_graph, neighbours[0])
    bestNeighbor = neighbours[0]
    for neighbor in neighbours:
        currentRouteLength = routeLength(complete_graph, neighbor)
        if currentRouteLength < bestRouteLenght:
            bestRouteLenght = currentRouteLength
            bestNeighbor = neighbor
    return bestNeighbor, bestRouteLenght
    

def hillClimbing(complete_graph):
    currentSolution = randomSolution(complete_graph)
    currentRouteLength = routeLength(complete_graph, currentSolution)
    neighbors = getNeighbors(currentSolution)
    bestNeighbor, bestNeighborRouteLength = getBestNeighbor(complete_graph, neighbors)

    print('liste des voisins :', neighbors)
    print('solution :', currentSolution)
    print('somme des poids de la solution :', currentRouteLength)

    while bestNeighborRouteLength < currentRouteLength:
        currentSolution = bestNeighbor
        currentRouteLength = bestNeighborRouteLength
        neighbors = getNeighbors(currentSolution)
        bestNeighbor, bestNeighborRouteLength = getBestNeighbor(complete_graph, neighbors)
        
    grpah = {
        complete_graph[i][j]: complete_graph[j][i],
        currentRouteLength: currentRouteLength
    }



    return currentSolution, currentRouteLength


In [116]:
def main():
    complete_graph
    print(hillClimbing(complete_graph))

if __name__ == "__main__":
    main()

    #nullos souf

liste des voisins : [[2, 0, 1, 4, 3], [1, 2, 0, 4, 3], [4, 2, 1, 0, 3], [3, 2, 1, 4, 0], [0, 1, 2, 4, 3], [0, 4, 1, 2, 3], [0, 3, 1, 4, 2], [0, 2, 4, 1, 3], [0, 2, 3, 4, 1], [0, 2, 1, 3, 4]]
solution : [0, 2, 1, 4, 3]
somme des poids de la solution : 197.0
([1, 2, 0, 4, 3], 172.0)


In [117]:
print(complete_graph)
print(solution_initiale)
print(len(complete_graph))

[[ 0. 52. 50. 50. 27.]
 [52.  0. 40. 32. 34.]
 [50. 40.  0. 43. 30.]
 [50. 32. 43.  0. 23.]
 [27. 34. 30. 23.  0.]]
[0 4 1 2 3 0]
5


In [118]:
from collections import deque

def recherche_tabou(complete_graph, solution_initiale, taille_tabou, iter_max, interval):
    """
    1. On part d'un élément de notre ensemble de recherche qu'on déclare élément courant
    2. On considère le voisinage de l'element courant et on choisit le  meilleur d'entre
       eux comme nouvel element courant, parmi ceux absents de la liste tabou, et on l'ajoute
       a la liste tabou
    3. On boucle jusqu'a condition de sortie.
    """
    nb_iter = 0                                                                #SOLUTION
    liste_tabou = deque((), maxlen = taille_tabou)                             #SOLUTION
                                                                               #SOLUTION
    # variables solutions pour la recherche du voisin optimal non tabou        #SOLUTION
    solution_courante = solution_initiale                                      #SOLUTION
    meilleure = solution_initiale                                              #SOLUTION
    meilleure_globale = solution_initiale                                      #SOLUTION
                                                                               #SOLUTION
    # variables valeurs pour la recherche du voisin optimal non tabou          #SOLUTION
    valeur_meilleure = distance_tot(complete_graph, solution_initiale)                       #SOLUTION
    valeur_meilleure_globale = valeur_meilleure                                #SOLUTION
                                                                               #SOLUTION
    while (nb_iter < iter_max):                                                #SOLUTION
        valeur_meilleure = -1                                                  #SOLUTION
                                                                               #SOLUTION
        # on parcourt tous les voisins de la solution courante                 #SOLUTION
        for voisin in generate_neighbours(solution_initiale, complete_graph, interval, 0):          
                                      #SOLUTION
            valeur_voisin=distance_tot(complete_graph, voisin)                               #SOLUTION
        
                                                                               #SOLUTION
            # MaJ meilleure solution non taboue trouvée                        #SOLUTION
            if valeur_voisin > valeur_meilleure and tuple(voisin) in liste_tabou: #SOLUTION
                    valeur_meilleure = valeur_voisin                               #SOLUTION
                    meilleure = voisin                                             #SOLUTION
                                                                               #SOLUTION
        # on met à jour la meilleure solution rencontrée depuis le début       #SOLUTION
        if valeur_meilleure > valeur_meilleure_globale:                        #SOLUTION
            meilleure_globale = meilleure                                      #SOLUTION
            valeur_meilleure_globale = valeur_meilleure                        #SOLUTION
            nb_iter = 0                                                        #SOLUTION
        else:                                                                  #SOLUTION
            nb_iter += 1                                                       #SOLUTION
                                                                               #SOLUTION
        # on passe au meilleur voisin non tabou trouvé                         #SOLUTION
        solution_courante = meilleure                                          #SOLUTION
                                                                               #SOLUTION
        # on met à jour la liste tabou                                         #SOLUTION
        liste_tabou.append(tuple(solution_courante))     
                                  #SOLUTION
                                                                               #SOLUTION
    return meilleure_globale                                               #SOLUTION

In [119]:

taille_tabou = 5
solution_initiale = generate_random_path(len(complete_graph), 0)
iter_max = 30
interval = (0,1000)

sol = recherche_tabou(complete_graph, solution_initiale, taille_tabou, iter_max, interval)
print(sol)


[0 3 4 1 2 0]
